### ISSUE TITLE
SCEst to SCL Compilation places variable outside of fork branch, causing syntax error

### ISSUE THREAD

**Issue by lken274** [kieler/semantics#119]
A basic invocation of two modules in parallel in SCEst:

```
module TopLevel:
    output received : integer;
    signal intermediate : integer in
    [
        run Producer [signal intermediate / produce];
    ]
        ||
    [
        run Consumer [signal intermediate / consume, received / received];
    ]
    end signal;
end module
```

Compiles to the following SCL:

```
module TopLevel
...
bool term2 = false;
fork
{
		...
		bool term1 = false;
		fork
		fork
			{
					@Producer_1
					{
						...
					}
			}
			par
			{
					@Consumer_2
					{
					        ...
					}
			}
			join ;
			term1 = true
		par
		...
		join
	}
	term2 = true        <<---------------------Syntax error!
par
...
join
```

I'm guessing that that assignment should occur one line above, before the closing brace. Manually moving this one line up seems to result in the behaviour I expect.

**Comment by a-sr** [comment]
Yes, it looks like the assignment is placed in the wrong scope.

Sadly, at the moment I do not have the time to track down the error in the transformation code but we will try to fix this issue somewhere in the future.

**Comment by lken274** [comment]
> Yes, it looks like the assignment is placed in the wrong scope.
> 
> Sadly, at the moment, I do not have the time to track down the error in the transformation code but we will try to fix this issue somewhere in the future.
> 
> Thank you for reporting your discovery.

Hi Alexander,

I have done some more experimenting and I believe the problem is more simple than this. By default, the parallel branch created by an output signal has no scoping braces:

```
output bool x = false, x_set = false;
output int x_cur, x_val;
bool term1 = false;
fork
	p;
	term1 = true
par
_l1:
	x = false;
	if !term1 {
		pause;
		goto _l1
}
join

```

If your first statement is something the introduces scoping braces, like a local signal or variable declaration, then the grammar assumes those braces belong to the parent module.

**Comment by a-sr** [comment]
I agree and reviewed your PR. It looks good.

Thank you for the fix. I will merge it as soon the CI checks are finished.
