### ISSUE TITLE
Exit transformation creates infinite self-loop

### ISSUE THREAD

**Issue by eNBeWe** [kieler/semantics#14]
Consider the following model

![FinalStateExit_before](https://user-images.githubusercontent.com/3796429/160396453-29ad4f38-b7e4-4041-bdd4-edcb8621a465.png)

```
scchart FinalStateExit {

  extern "foo" foo

  output bool O

  initial state A {
    exit do foo()
    
    initial state S1
    go to S2
    
    final state S2 {
      entry do O = true
    } 
  }
}
```

When this model is translated, the exit transformation creates a new final state with an immediate self-transition. 
![FinalStateExit_after](https://user-images.githubusercontent.com/3796429/160396906-10257e1c-64b5-4e29-8e55-01118b040780.png)

That is obviously not a proper model anymore.

**Comment by eNBeWe** [comment]
I think I traced the issue to
https://github.com/kieler/semantics/blob/16a2eabc6ddf9e1a63d3885efe19bb59faf9e9d7/plugins/de.cau.cs.kieler.sccharts/src/de/cau/cs/kieler/sccharts/processors/Exit.xtend#L143

The getOrCreateSimpleFinalState doesn't pick up the existing final state, because that isn't simple. Instead it finds the newly created "_Done" state and messes that up.

**Comment by a-sr** [comment]
Thanks for hunting it down so far. We will look into it.
