### ISSUE TITLE
[KISEMA-1580] Make SCCharts highlighting framework LS ready

### ISSUE THREAD

**Issue by fabianheyer** [kieler/semantics#41]
_[Issue KISEMA-1580 migrated from JIRA, first reported on 2020-08-07]_

Currently the `SCChartsLSDiagramHighlighter` is just a copy of the `SCChartsHighlighter`.

The `LSHighlighter` should use the normal one in some way.

**Comment by soerendomroes** [comment]
This is already fixed with 09a902f5c06529d64fe26673c99c00ff97286a7b
